name: NPM Package
on:
  release:
    types: [created]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        registry-url: 'https://registry.npmjs.org'
        
    - name: install dependencies
      run: npm ci
    
    - name: test
      run: npm run test
    
    - name: set version
      run: npm --no-git-tag-version version ${GITHUB_REF#refs/*/}
      
    - name: sonar scanner
      run: npm run sonar -- -Dsonar.login=${{ secrets.SONAR_AUTH_TOKEN }}
      
    - name: publish to npmjs.com
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
    
